name: Tests

on:
  push:
    branches:
      - main

jobs:
  unit-test:
    runs-on: ubuntu-20.04
    container: docker://epitechcontent/epitest-docker

    steps:
      - name: Repository Checkout
        uses: actions/checkout@v3

      - name: Run tests
        shell: bash
        run: make tests_run
      
      - name: Run converage
        shell: bash
        run: make coverage